export interface ArticleInterface {
  _id?:string;
  BLS_Key:string;
  nameArticle:string;
  kcal:number;
  proteinMg:number;
  fettMg:number;
  kohlenhydrateMg:number;
  ballaststoffeMg:number;
  vitaminARetinolUg:number;
  vitaminDUg:number;
  vitaminB1UG:number;
  vitaminB2Ug:number;
  vitaminB6Ug:number;
  vitaminB12Ug:number;
  vitaminCUg:number;
  natriumMg:number;
  kaliumMg:number;
  calciumMg:number;
  magnesiumMg:number;
  phosphorMg:number;
  schwefelMg:number;
  chloridMg:number;
  eisenUg:number;
  zinkUg:number;
  KupferUg:number;
  fluoriUg:number;
  fruchtoseMg:number;
  lactoseMg:number;
  zuckerMg:number;
  gesFettMg:number;
  mehrfachUnFettMg:number;
  omgega3Mg:number;
  omega6Mg:number;
  cholesterinMg:number;
  broteinheitenBE:number;
  kochsalzMg:number;
  einfachUnFettMg:number;
  price:number;
  isEdited:boolean;
  articleNumber:string;
  supplier:string;
  allergenes:{_id:string,name_allergene:string}[];
}


